#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

DATA_DIR="${CONFIG_DIR}" && export DATA_DIR
DEBUG="False"            && export DEBUG

cd "${APP_DIR}" || exit 1

# shellcheck disable=SC2086
exec s6-setuidgid hotio hypercorn --quic-bind 0.0.0.0:8000 --bind 0.0.0.0:8000 --access-logfile "${CONFIG_DIR}/logs/access.log" ${ARGS} conreq.asgi:application
