#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

DATA_DIR="${CONFIG_DIR}" && export DATA_DIR
DEBUG="False"            && export DEBUG

cd "${APP_DIR}" || exit 1

python3 ./manage.py migrate --noinput
python3 ./manage.py collectstatic --link --noinput
python3 ./manage.py compress

chown -R hotio:hotio "${CONFIG_DIR}"

# shellcheck disable=SC2086
s6-setuidgid hotio python3 ./manage.py run_huey --quiet &
